#!/usr/bin/env python3

# This program was written by Asish Balasundaram (z5430777)
# This file is the program that lists out the commits in the cur working branch
# along with the commit messages

import sys, os

if __name__ == "__main__":
    # Need to check if .grip exists, and only continue if it does 
    if (not os.path.isdir('.grip')):
        print('grip-log: error: grip repository directory .grip not found',
            file = sys.stderr)
        sys.exit(1)
    # Getting the current working branch name
    curBranchReader = open('.grip/_curBranch')
    curBranch = curBranchReader.readline()
    curBranchReader.close()

    # Now we print out the commits in the cur working branch and the commit msgs
    # First we get a list of all the commits in the current working branch
    curBranchCommits = sorted(map(lambda n : int(n), os.listdir(f".grip/branches/{curBranch}")))
    for commitNum in reversed(curBranchCommits):
        # We can now get the commit message for the commit we are focusing on
        commitMsgReader = open(f".grip/branches/{curBranch}/{commitNum}/commitMsg")
        commitMsg = commitMsgReader.readline()
        commitMsgReader.close()
        
        # Finally we print the commit Id and commit message one at a time
        print(f"{commitNum} {commitMsg}")
